// <auto-generated />
using System;
using Kavopici.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kavopici.Migrations
{
    [DbContext(typeof(KavopiciDbContext))]
    partial class KavopiciDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Kavopici.Models.CoffeeBlend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoastLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roaster")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("CoffeeBlends");
                });

            modelBuilder.Entity("Kavopici.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlendId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "SessionId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Stars", "[Stars] >= 1 AND [Stars] <= 5");
                        });
                });

            modelBuilder.Entity("Kavopici.Models.RatingTastingNote", b =>
                {
                    b.Property<int>("RatingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TastingNoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingId", "TastingNoteId");

                    b.HasIndex("TastingNoteId");

                    b.ToTable("RatingTastingNotes");
                });

            modelBuilder.Entity("Kavopici.Models.TastingNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TastingNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ovocná"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ořechová"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Čokoládová"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karamelová"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Květinová"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kořeněná"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Citrusová"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Medová"
                        });
                });

            modelBuilder.Entity("Kavopici.Models.TastingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlendId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlendId");

                    b.ToTable("TastingSessions");
                });

            modelBuilder.Entity("Kavopici.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kavopici.Models.CoffeeBlend", b =>
                {
                    b.HasOne("Kavopici.Models.User", "Supplier")
                        .WithMany("SuppliedBlends")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Kavopici.Models.Rating", b =>
                {
                    b.HasOne("Kavopici.Models.CoffeeBlend", "Blend")
                        .WithMany("Ratings")
                        .HasForeignKey("BlendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kavopici.Models.TastingSession", "Session")
                        .WithMany("Ratings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kavopici.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blend");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kavopici.Models.RatingTastingNote", b =>
                {
                    b.HasOne("Kavopici.Models.Rating", "Rating")
                        .WithMany("RatingTastingNotes")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kavopici.Models.TastingNote", "TastingNote")
                        .WithMany("RatingTastingNotes")
                        .HasForeignKey("TastingNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("TastingNote");
                });

            modelBuilder.Entity("Kavopici.Models.TastingSession", b =>
                {
                    b.HasOne("Kavopici.Models.CoffeeBlend", "Blend")
                        .WithMany("Sessions")
                        .HasForeignKey("BlendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blend");
                });

            modelBuilder.Entity("Kavopici.Models.CoffeeBlend", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Kavopici.Models.Rating", b =>
                {
                    b.Navigation("RatingTastingNotes");
                });

            modelBuilder.Entity("Kavopici.Models.TastingNote", b =>
                {
                    b.Navigation("RatingTastingNotes");
                });

            modelBuilder.Entity("Kavopici.Models.TastingSession", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Kavopici.Models.User", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("SuppliedBlends");
                });
#pragma warning restore 612, 618
        }
    }
}
